In [1]:
a = 10

In [1]:
import os

In [8]:
os.chdir(" ")

'C:\\Users\\visa'

In [2]:
a 

10

This is my first code in python - 

In [4]:
import numpy as np 
import pandas as pd
import sklearn as sklearn

In [9]:
a= 10
b=20
a+b

30

In [16]:
a = (10,20,30)
a

(10, 20, 30)

In [19]:
a[2] = 20

TypeError: 'tuple' object does not support item assignment

In [17]:
b = [ 10,20,30]
b

[10, 20, 30]

In [24]:
b.pop()

40

In [25]:
b

[10, 20]

In [27]:
import numpy as np

In [33]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [35]:
a=(10,20,30,30)
b=(40,50,60)
a+b

(10, 20, 30, 30, 40, 50, 60)

In [51]:
a = np.array([1,2,3])
b = np.array([5,6,7])
a+b

array([ 6,  8, 10])

In [52]:
a = np.array([[a],[b]])

In [53]:
a

array([[[1, 2, 3]],

       [[5, 6, 7]]])

In [4]:
import pandas as pd

In [37]:
import os

In [2]:
os.chdir("D:\\Data Science - Course\\Python")

In [5]:
df1 = pd.read_csv("Churn.csv")

In [6]:
pd.crosstab(df1.State, df1.Churn)

Churn   0   1
State        
AK     49   3
AL     72   8
AR     44  11
AZ     60   4
CA     25   9
CO     57   9
CT     62  12
DC     49   5
DE     52   9
FL     55   8
GA     46   8
HI     50   3
IA     41   3
ID     64   9
IL     53   5
IN     62   9
KS     57  13
KY     51   8
LA     47   4
MA     54  11
MD     53  17
ME     49  13
MI     57  16
MN     69  15
MO     56   7
MS     51  14
MT     54  14
NC     57  11
ND     56   6
NE     56   5
NH     47   9
NJ     50  18
NM     56   6
NV     52  14
NY     68  15
OH     68  10
OK     52   9
OR     67  11
PA     37   8
RI     59   6
SC     46  14
SD     52   8
TN     48   5
TX     54  18
UT     62  10
VA     72   5
VT     65   8
WA     52  14
WI     71   7
WV     96  10
WY     68   9

In [40]:
df1.head()

Account Length  VMail Message  Day Mins  Eve Mins  Night Mins  Intl Mins  \
0             128             25     265.1     197.4       244.7       10.0   
1             107             26     161.6     195.5       254.4       13.7   
2             137              0     243.4     121.2       162.6       12.2   
3              84              0     299.4      61.9       196.9        6.6   
4              75              0     166.7     148.3       186.9       10.1   

   CustServ Calls  Churn  Intl Plan  VMail Plan    ...     Day Charge  \
0               1      0          0           1    ...          45.07   
1               1      0          0           1    ...          27.47   
2               0      0          0           0    ...          41.38   
3               2      0          1           0    ...          50.90   
4               3      0          1           0    ...          28.34   

   Eve Calls  Eve Charge  Night Calls  Night Charge  Intl Calls  Intl Charge  \
0         99       16.78           91         11.01           3         2.70   
1        103       16.62          103         11.45           3         3.70   
2        110       10.30          104          7.32           5         3.29   
3         88        5.26           89          8.86           7         1.78   
4        122       12.61          121          8.41           3         2.73   

   State Area Code     Phone  
0     KS       415  382-4657  
1     OH       415  371-7191  
2     NJ       415  358-1921  
3     OH       408  375-9999  
4     OK       415  330-6626  

[5 rows x 21 columns]

In [42]:
df2 = df1.drop(["Account Length","Mail Message"], axis=1)

In [47]:
df1.columns

Index(['Account Length', 'VMail Message', 'Day Mins', 'Eve Mins', 'Night Mins',
       'Intl Mins', 'CustServ Calls', 'Churn', 'Intl Plan', 'VMail Plan',
       'Day Calls', 'Day Charge', 'Eve Calls', 'Eve Charge', 'Night Calls',
       'Night Charge', 'Intl Calls', 'Intl Charge', 'State', 'Area Code',
       'Phone'],
      dtype='object')

In [59]:

for m in df1.columns:
    print (df1[m].name , df1[m].dtype)

Account Length int64
VMail Message int64
Day Mins float64
Eve Mins float64
Night Mins float64
Intl Mins float64
CustServ Calls int64
Churn int64
Intl Plan int64
VMail Plan int64
Day Calls int64
Day Charge float64
Eve Calls int64
Eve Charge float64
Night Calls int64
Night Charge float64
Intl Calls int64
Intl Charge float64
State object
Area Code int64
Phone object


In [67]:
print(df1["Phone"].dtype)

object


In [68]:
import matplotlib.pyplot as plt

In [88]:
plt.hist( df1["Account Length"], bins=20)

(array([  43.,   56.,   96.,  131.,  202.,  297.,  328.,  406.,  396.,
         371.,  349.,  226.,  167.,  119.,   69.,   42.,   17.,   11.,
           5.,    2.]),
 array([   1. ,   13.1,   25.2,   37.3,   49.4,   61.5,   73.6,   85.7,
          97.8,  109.9,  122. ,  134.1,  146.2,  158.3,  170.4,  182.5,
         194.6,  206.7,  218.8,  230.9,  243. ]),
 <a list of 20 Patch objects>)

In [89]:
plt.show()

In [90]:
plt.boxplot( df1["Day Calls"], 1)

{'boxes': [<matplotlib.lines.Line2D at 0x19148356a90>],
 'caps': [<matplotlib.lines.Line2D at 0x1914835eda0>,
 'fliers': [<matplotlib.lines.Line2D at 0x19148369d68>],
 'means': [],
 'medians': [<matplotlib.lines.Line2D at 0x19148364e10>],
 'whiskers': [<matplotlib.lines.Line2D at 0x19148356c18>,
  <matplotlib.lines.Line2D at 0x1914835ec88>]}

In [91]:
plt.show()

In [92]:
plt.scatter(df1["Day Calls"], df1["Eve Calls"])

In [93]:
plt.show()

In [69]:
np.corrcoef(df1["Eve Charge"],df1["Eve Calls"] )

array([[ 1.        , -0.01142289],
       [-0.01142289,  1.        ]])

In [70]:
from scipy.stats.stats import pearsonr  

In [75]:
plt.scatter(df1["Eve Charge"],df1["Eve Calls"])

In [86]:
plt.show()

In [77]:
plt.hist(df1["Eve Charge"], bins=10)

(array([   2.,   21.,   87.,  339.,  742.,  931.,  717.,  373.,  100.,   21.]),
 array([  0.   ,   3.091,   6.182,   9.273,  12.364,  15.455,  18.546,
         21.637,  24.728,  27.819,  30.91 ]),
 <a list of 10 Patch objects>)

In [78]:
plt.show()

In [79]:
plt.boxplot(df1["Eve Charge"], 1)

{'boxes': [<matplotlib.lines.Line2D at 0x19145852b70>],
 'caps': [<matplotlib.lines.Line2D at 0x19145858e80>,
 'fliers': [<matplotlib.lines.Line2D at 0x19145864e48>],
 'means': [],
 'medians': [<matplotlib.lines.Line2D at 0x1914585fef0>],
 'whiskers': [<matplotlib.lines.Line2D at 0x19145852cf8>,
  <matplotlib.lines.Line2D at 0x19145858d68>]}

In [80]:
plt.show()

In [94]:
import numpy as np
import matplotlib.pyplot as plt


N = 50
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
area = np.pi * (15 * np.random.rand(N))**2  # 0 to 15 point radiuses

plt.scatter(x, y, s=area, c=colors, alpha=0.5)
plt.show()

In [95]:
import sklearn

In [96]:
from sklearn import datasets

In [97]:
from sklearn.ensemble import RandomForestClassifier

In [98]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
from sklearn.cross_validation import train_test_split

In [101]:
from SVM import SVC

In [106]:
iris = datasets.load_iris()

In [104]:
data

{'DESCR': 'Iris Plants Database\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n

In [107]:

iris_data = pd.DataFrame(iris.data)
target = iris.target

In [108]:
iris_data.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [109]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [111]:
from sklearn.cross_validation import train_test_split

In [112]:

X_train, X_test, y_train, y_test = train_test_split(iris_data, target, test_size=0.3, random_state=42)

In [113]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [114]:
y_pred = rf.predict(X_test)

In [115]:
from sklearn.metrics import confusion_matrix

In [117]:
confusion_matrix( y_test, y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [118]:
iris_d = pd.read_csv("iris.csv")

In [119]:
iris_d.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [120]:
iris_data = iris_d.drop("Species", axis=1)

In [121]:
iris_data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [122]:
target = iris_d["Species"]

In [7]:
target.count()

NameError: name 'target' is not defined

In [124]:
x_train, x_test, y_train, y_test = train_test_split( iris_data, target, test_size=0.3, random_state= 123)

In [125]:
rf1 = RandomForestClassifier(n_estimators=100)
rf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [126]:
y_pred1 = rf1.predict(x_test)

In [127]:
confusion_matrix( y_test, y_pred1)

array([[ 3, 12,  3],
       [ 1,  5,  4],
       [ 6,  2,  9]])